---
- hosts: localhost
  tasks:
          - name: Generate an OpenSSL private key with a different size (2048 bits)
            openssl_privatekey:
                    path: /etc/ssl/private/ansible.com.pem
          - name: Generate an OpenSSL public key in pem format
            openssl_publickey:
                    path: /etc/ssl/public/ansible.com.pem
                    privatekey_path: /etc/ssl/private/ansible.com.pem
                    force: yes
            openssh_cert:
                  type: host
                  signing_key: /etc/ssl/private/ansible.com.pem
                  public_key: /etc/ssl/public/ansible.com.pem
                  path: /etc/ssl/certificate
                  valid_from: always
                  valid_to: forever
